### ISSUE TITLE
デモを簡素化します / Simplify the demo

### ISSUE THREAD

**Issue by hanamura-geek-guild** [geek-guild/smalltrain#5]
#### Docker デモスクリプトを簡素化します。
```
smalltrain/docker/smalltrain/run_smalltrain.sh
```

- 具体的には、テストオペレーション:
```
# Test operation
# 1. Debug with small data set
OPERATION_ID=IR_2D_CNN_V2_l49-c64_TUTORIAL-DEBUG-WITH-SMALLDATASET-20200708-TRAIN
```
を実行したら、デモを一旦停止するようにします。(スクリプトからexitします)

- 学習デモ以下は、マニュアル的に実行して頂くようになります。
```
# ここ以下
# 2. Training example
```

- 理由: Training exampleは長時間(1時間以上)の処理になるので、デモには適さないと考えました。

**Comment by mikibito** [comment]
Do we need change documentation such as getting started and other pages? if so, could you tell me the part which require changes.

**Comment by hanamura-geek-guild** [comment]
@mikibito No, we don't because this operation(`2. Training example`) is originally not explained in any documentation.

**Comment by hanamura-geek-guild** [comment]
We will release the update for this issue as overwriting release/v0.2.0 again because this is a small update.
/ このissueに関する更新は軽微ですので、release/v0.2.0として上書きリリースします。

**Comment by hanamura-geek-guild** [comment]
Merged to master. I'll close this.
